name: ntfy_discord_bot
description: An advanced modal-based bot for interacting with the ntfy.sh API
version: 0.2.1
homepage: https://www.github.com/jr1221/ntfy_discord_bot
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  nyxx:
  nyxx_interactions:
  nyxx_commands:
  ntfy_dart:
    git:
      url: https://github.com/jr1221/ntfy_dart.git

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0
