name: ntfy_discord_bot
description: An advanced modal-based bot for interacting with the ntfy.sh API
version: 0.2.1
homepage: https://www.github.com/jr1221/ntfy_discord_bot
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  nyxx:
      git:
        url: https://github.com/nyxx-discord/nyxx.git
        ref: next
  nyxx_commands:
    git:
      url: https://github.com/nyxx-discord/nyxx-commands.git
      ref: feat/nyxx-6.0.0
  ntfy_dart:
    git:
      url: https://github.com/jr1221/ntfy_dart.git
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.3
dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0
  drift_dev: ^2.9.0
  build_runner: ^2.4.5

dependency_overrides:
  nyxx:
      git:
        url: https://github.com/nyxx-discord/nyxx.git
        ref: next

    