name: ntfy_discord_bot
description: An advanced modal-based bot for interacting with the ntfy.sh API
version: 0.0.2
homepage: https://www.github.com/jr1221/ntfy_discord_bot
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  nyxx: ^4.4.0
  nyxx_commands:
    git:
      url: https://github.com/nyxx-discord/nyxx_commands
      ref: next
  ntfy_dart:
    git:
      url: https://github.com/jr1221/ntfy_dart

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
