name: ntfy_discord_bot
description: An advanced modal-based bot for interacting with the ntfy.sh API
version: 0.0.3
homepage: https://www.github.com/jr1221/ntfy_discord_bot
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  nyxx:
  nyxx_interactions:
  nyxx_commands: ^5.0.1
  ntfy_dart:
    git:
      url: https://github.com/jr1221/ntfy_dart

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0
